### ISSUE TITLE
star sm-s210i bluetooth 

### ISSUE THREAD

**Issue by daniellizik** [auctifera-josed/starprnt#26]
possibly related to #3 but for a different model.

```yml
cordova: 8.0.0
cordova-ios: 4.5.5
cordova-plugin-starprnt: 2.2.0
```

Testing on star sm-s210i and ipad 6. The printer pairs via bluetooth fine, but if I call `starprnt.portDiscovery` none of the callbacks are ever invoked. This happens regardless of the emulation mode (starPRNT or esc/pos)

<img width="575" alt="screen shot 2018-11-19 at 17 28 40" src="https://user-images.githubusercontent.com/10506366/48694749-92c08800-ec20-11e8-9a8a-855c79b0ced2.png">
